# ===============================
# Database Configuration
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root

  # ===============================
  # JPA Configuration
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

app:
  jwtExpirationMs: 900000         # 15 minutes for access token
  jwtRefreshExpirationMs: 604800000  # 7 days for refresh token

#springdoc:
#  api-docs:
#    enabled: true   # keep automatic generation on
#    #additional-openapi-yaml: classpath:/static/openapi.yml
#  swagger-ui:
#    url: /openapi.yml  # Load your custom OpenAPI YAML file
#    path: /swagger-ui.html
#http://localhost:8080/swagger-ui/index.html  access this url to see swagger ui